export const INITIATE_MOVIE_REQUEST = 'INITIATE_MOVIE_REQUEST';
export const MOVIE_REQUEST_SUCCESS = 'MOVIE_REQUEST_SUCCESS';
export const MOVIE_REQUEST_FAILED = 'MOVIE_REQUEST_FAILED';
export const SHOW_PRE_LOADER = 'SHOW_PRE_LOADER';
export const ADD_TO_WATCH_LIST = 'ADD_TO_WATCH_LIST';
export const REMOVE_FROM_WATCH_LIST = 'REMOVE_FROM_WATCH_LIST';
